name: Test
on: [ pull_request, push ]

jobs:
  test:
    strategy:
      matrix:
        java: [ 11,17 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: prepare gradle wrapper
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: clean
        run: ./gradlew clean
      - name: build
        run: ./gradlew build
      - name: clean log cache (Linux & macOS)
        if: ${{ runner.os != 'Windows' }}
        run: |
          rm -rf src/test/resources/logs
          mkdir ./src/test/resources/logs
      - name: clean log cache (Windows)
        if: ${{ runner.os == 'Windows' }}
        run: |
          if (Test-Path '.\src\test\resources\logs') {
            rd /s /q src\test\resources\logs
          }
          mkdir .\src\test\resources\logs
      - name: test
        run: ./gradlew test
      - name: capture test log (Linux)
        if: ${{ matrix.java == '17' && runner.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: test-log-linux-jdk17
          path: src/test/resources/logs/
      - name: capture test log (Linux)
        if: ${{ matrix.java == '11' && runner.os == 'Linux' }}
        uses: actions/upload-artifact@v2
        with:
          name: test-log-linux-jdk11
          path: src/test/resources/logs/
      - name: capture test log (macOS)
        if: ${{ matrix.java == '17' && runner.os == 'macOS' }}
        uses: actions/upload-artifact@v2
        with:
          name: test-log-macos-jdk17
          path: src/test/resources/logs/
      - name: capture test log (macOS)
        if: ${{ matrix.java == '11' && runner.os == 'macOS' }}
        uses: actions/upload-artifact@v2
        with:
          name: test-log-macos-jdk11
          path: src/test/resources/logs/
      - name: capture test log (Windows)
        if: ${{ matrix.java == '17' && runner.os == 'Windows' }}
        uses: actions/upload-artifact@v2
        with:
          name: test-log-windows-jdk17
          path: src\test\resources\logs\
      - name: capture test log (Windows)
        if: ${{ matrix.java == '11' && runner.os == 'Windows' }}
        uses: actions/upload-artifact@v2
        with:
          name: test-log-windows-jdk11
          path: src\test\resources\logs\
